# Generated by Django 4.2 on 2023-06-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
